### ISSUE TITLE
Export `maic_unanchored_tte` etc?

### ISSUE THREAD

**Issue by gravesti** [hta-pharma/maicplus#102]
if this is not exported, this wrapper becomes a blackbox.
How do users know what is done behind the scenes. Only way is to download the whole package and dig into the code.

_Originally posted by @MikeJSeo in https://github.com/hta-pharma/maicplus/pull/93#discussion_r1597993415_

**Comment by hoppanda** [comment]
team discussed and decided to export, mark as internal function, documentation need to be clear and state that these functions could be changed in a future version

**Comment by MikeJSeo** [comment]
team discussed again and decided not to export. Instead, maybe adding some descriptions the the wrapper function what it does
