### ISSUE TITLE
Hex sticker

### ISSUE THREAD

**Issue by gravesti** [hta-pharma/maicplus#115]
Suggestions welcome!

@hoppanda to get some AI suggestions

**Comment by gravesti** [comment]
![image](https://github.com/user-attachments/assets/454f3918-2e43-4855-8f2c-b53fc5f179f7)

**Comment by gravesti** [comment]
![image](https://github.com/user-attachments/assets/423ad037-f551-4087-aa88-90251c15a662)

**Comment by hoppanda** [comment]
by voting, 2 vs 1, hence we have the second icon
