### ISSUE TITLE
fix output for inferential$report_overall_robustCI

### ISSUE THREAD

**Issue by MikeJSeo** [hta-pharma/maicplus#132]
<img width="623" alt="image" src="https://github.com/user-attachments/assets/2431d8db-5eed-4b6e-bfad-a34e04120754">

- add in unadjusted A vs B. This is quite important!
- fix the indentation issue (i.e. space between 0.46 [0.23)
- renumber the rownumbers 1:7

**Comment by hoppanda** [comment]
resolved, and report/summary function will be standalone
