### ISSUE TITLE
issue with bootstrap anchored

### ISSUE THREAD

**Issue by MikeJSeo** [hta-pharma/maicplus#134]
- bucher function does not work when it is inside stat_fun for anchored.
- If the function is called outside, it seems to work.

Try adding the following code in maic_anchored.R

    print("trial")
    AC_bootstrap <- list(est = res_AC$est, se = sd(boot_res$t[,4]))
    weighted_bucher_bootstrap <- bucher(AC_bootstrap, res_BC)
    print(exp(weighted_bucher_bootstrap$ci_l))
    print(exp(weighted_bucher_bootstrap$ci_u))
    print("end trial")

<img width="540" alt="image" src="https://github.com/user-attachments/assets/0dcd5b53-bb01-43e1-b932-15c6c999313f">

We get correct confidence interval when you do this. Confidence interval is very similar to robust C.I.

**Comment by gravesti** [comment]
Try just using AvB point estimate
