### ISSUE TITLE
typo in maic_unanchored

### ISSUE THREAD

**Issue by MikeJSeo** [hta-pharma/maicplus#135]
<img width="515" alt="image" src="https://github.com/user-attachments/assets/5cc3c4a9-92cd-476b-8aa4-17ead654f75c">

- should be report_boot$`HR[95% CI]`[1] <- do.call(sprintf, args = c(list(fmt = "%.2f[%.2f;%.2f]"), boot_res_AB[**c(1,3,4)]**))

**Comment by hoppanda** [comment]
it is resolved
