### ISSUE TITLE
boot_strata changes

### ISSUE THREAD

**Issue by gravesti** [hta-pharma/maicplus#140]
- [ ] fix check in estimate weights to first check n bootstrap samples > 0 or non-null, then check bootstrata column exists
- [ ] set defatul boot_strata = NULL
- [ ] make example showing how to use boot_strata

**Comment by MikeJSeo** [comment]
can we also put uppercase ARM, USUBJID in estimate_weights function? would this fix the issue?

**Comment by kurttaylor** [comment]
boot_strata = NULL should definitely be default to prevent older code from erroring!
