### ISSUE TITLE
Add NICE survey about ESS

### ISSUE THREAD

**Issue by miranta-antoniou-roche** [hta-pharma/maicplus#16]

**Comment by miranta-antoniou-roche** [comment]
@hoppanda @gravesti @MikeJSeo 

Hello All, 

I was thinking that we could add a footnote to the plot_weights function in the matching.R program about the NICE survey 2021. I think it would be useful for the users. What do you think? 

Maybe something like the following text: 

**According to a [ survey of NICE's technology appraisals](https://onlinelibrary.wiley.com/doi/full/10.1002/jrsm.1511) conducted in 2021: 
''In most applications, weighting considerably reduces the effective sample size from the original AC sample size. The median percentage reduction is 58% (range: 7.9%–94.1%; interquartile range: 42.2%–74.2%). The final effective sample sizes are also representative of those in the technology appraisals, which are also small (median: 80; range: 4.8–639; interquartile range: 37–174)''. Therefore, an ESS reduction up to ~60% is not unexpected based on the 2021 survey, whereas a reduction of >75% is less common and it may be considered suboptimal.** 

I tried to find a way to add a footnote to the histogram but I didn't manage until now as it is not based on the ggplot.

**Comment by MikeJSeo** [comment]
Hi Miranta, I will add a ggplot in the package and we can have an option to print this text :)

**Comment by MikeJSeo** [comment]
The paper you cite from (Remiro et al) uses 13 studies that have ESS to provide this.
I can't seem to find the source for this though.
I found an older publication: [phillipo](https://www.researchgate.net/publication/332779985_Population_Adjustment_Methods_for_Indirect_Comparisons_A_Review_of_National_Institute_for_Health_and_Care_Excellence_Technology_Appraisals)
that uses 9 studies that have ESS.
Any idea where these numbers are from?

**Comment by MikeJSeo** [comment]
Yea they don't provide a source for it. Just wondering where they got it from.

**Comment by miranta-antoniou-roche** [comment]
I would assume that Remiro et al. did this survey and therefore they don't provide a reference for that.

**Comment by MikeJSeo** [comment]
I think we can close this one :)
