### ISSUE TITLE
not true that supports >= 3.6

### ISSUE THREAD

**Issue by Polkas** [hta-pharma/maicplus#172]
https://github.com/hta-pharma/maicplus/blob/d44892488b603cdcd495e3810067ccd356af4869/DESCRIPTION#L47

Unfortunatelly one of the problem is  taht the |> is used in a few places so lower R versions are not supported / can not be installed. There may be more issues for 3.6.

**Comment by Polkas** [comment]
Please consider adding the new github actions for 3.6.

**Comment by gravesti** [comment]
Thanks @Polkas we will update accordingly

**Comment by gravesti** [comment]
Resolved in #173 to require higher R version (but also remove pipes)
