### ISSUE TITLE
Function (from flexsurvplus package) to simulate Survival data

### ISSUE THREAD

**Issue by miranta-antoniou-roche** [hta-pharma/maicplus#59]
The FlexsurvPlus package provides a function that simulates survival data with correlated time to progression and overall survival times.

Here is the link: https://roche.github.io/flexsurvPlus/main/reference/sim_adtte.html

The simulation times are derived from formulas in Austin 2012 adapted to enable correlations between endpoints. Austin, P.C. (2012), Generating survival times to simulate Cox proportional hazards models with time‐varying covariates. Statist. Med., 31: 3946-3958. https://doi.org/10.1002/sim.5452

Maybe we can consider using this available function?

**Comment by hoppanda** [comment]
discussed in the team meeting, @MikeJSeo will evaluate to see if anything can be adopted in data_generation.R. New issue will be open in that case
