### ISSUE TITLE
function naming style

### ISSUE THREAD

**Issue by gravesti** [hta-pharma/maicplus#6]
I'd like to ask to review the idea of using `function.name()` for exported functions. I think this naming style may lead to confusion about S3 methods for the user and for R/documentation/checks.

Is there a need to differentiate internal objects and functions with camel versus dots in names?
@hoppanda @MikeJSeo

**Comment by hoppanda** [comment]
will change cross the broad now

**Comment by hoppanda** [comment]
changed
